language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
script:
    - bundle install
    - bundle exec rake pod:install > /dev/null
    - bundle exec rake spec
    - rm -rf build/
    - rm -rf vendor/build/
    - rm -rf vendor/Pods/
    - bundle exec rake pod:install osx=true > /dev/null
    - bundle exec rake spec osx=true
